### ISSUE TITLE
Rules integration: Provide a rules action for sending an API call

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/cmrf_core#12]
cmrf_rules should provide a rules action to send an API call with the following Rules action parameters:
- CiviMRF profile
- API entity
- API action
- API parameters (e.g. as a JSON-formatted string)
- API options (e.g. as a JSON-formatted string)

The action should provide the call as a variable that may be inspected using the already existing tokens for the `civimrf_call` rules data type.

**Comment by jensschuppe** [comment]
@jaapjansma Review welcome for https://github.com/CiviMRF/cmrf_core/commit/164e4a375d50fe42b19b54957c681abf8d511f57.

**Comment by jaapjansma** [comment]
Looks good to me.

**Comment by jensschuppe** [comment]
Thanks @jaapjansma - merged into 7.x-dev and added the issue to the next [release notes draft](https://github.com/CiviMRF/cmrf_core/releases/tag/untagged-b26fba197b375f1c6ccc) for changelog reference.

**Comment by jensschuppe** [comment]
This got released with 0.5 already.
