### ISSUE TITLE
Webform integration: Prefill webform with hash-token data

### ISSUE THREAD

**Issue by bjendres** [CiviMRF/cmrf_core#14]
The ``7.x`` module  ``cmrf_webform`` should be able to pre-fill the form with data from CiviCRM, if it is called with a CiviCRM hash-token.

**Comment by jaapjansma** [comment]
This would be nice.

**Comment by jensschuppe** [comment]
Detailed requirements (as discussed with @systopia):
- (De-)activateable configurable API call for retrieving default values (defaults to `Contact.getsingle`)
- The contact hash (`hash`) is the only parameter
- Set Webform default values for matching response parameters == component names
- If a non-allowed value is to be set, let the Drupal Form API do their stuff
- On failure, "default" (Webform) default values are being set
- All this is only available if the Webform is set to be sent back to CiviCRM using CiviMRF

**Comment by jensschuppe** [comment]
@systopia This is available for real world testing in [7.x-0.7-alpha1](https://github.com/CiviMRF/cmrf_core/releases/tag/7.x-0.7-alpha1).

**Comment by bjendres** [comment]
Seems to work nicely so far - except for one crucial thing: It doesn't fill hidden fields. That would be *very* important if you want to e.g. fill and later submit the ``contact_id``, but prevent the user from injecting their own.

@jensschuppe: Could you have a look at this as soon as possible, please?

**Comment by jensschuppe** [comment]
@systopia This should work with 1ae2466b5dbc6cd833639b94cdf754ee19088a99. "Hidden" components do not respect a `#default_value` but need a `#value` to be set (See [Drupal Form API Reference for `value` form elements](https://api.drupal.org/api/drupal/developer%21topics%21forms_api_reference.html/7.x#val))
