### ISSUE TITLE
New module installation expects a default profile

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/cmrf_core#16]
When installing the module on a new Drupal site, there is no default profile, but the code expects one to exist. The module is not usable until a profil is being created and set as default (e.g. in the database or by calling custom PHP code).

Creating a default profile when installing seems a quick solution, but maybe I missed something @jaapjansma?

I will create a PR for the `hook_install()` implementation though.

**Comment by jaapjansma** [comment]
@jensschuppe No you didn't miss anything. Thanks for your fix.

**Comment by jensschuppe** [comment]
Thanks, merged into 7.x-dev.
