### ISSUE TITLE
Webform integration: select options from CiviCRM

### ISSUE THREAD

**Issue by bjendres** [CiviMRF/cmrf_core#2]
Extend the ``cmrf_webform`` module so that select option sets used for webform select components can be created based on arbitrary CiviCRM API calls.

**Comment by bjendres** [comment]
@jaapjansma: @jensschuppe has already implemented it, push is coming up...

**Comment by jaapjansma** [comment]
great!

**Comment by jensschuppe** [comment]
Branch ``7.x-dev_2`` implements configurable CiviCRM API calls, whose results can be used as pre-built select options for Webform select components. Definitions of such select option sets are global and overridable per CMRF core profile. The profile used for submission via CiviMRF Webform integration is also used for retrieving select options for select components on that Webform node. An additional API parameter ``_cmrf_language`` is submitted for the CiviCRM instance to deliver localized results (e.g. using an API wrapper for custom APIs).
Reviews welcome before merging with ``7.x-dev``.

**Comment by jensschuppe** [comment]
See PR #4.
