### ISSUE TITLE
[Views integration] field names not retrieved correctly for some entities (Views fields have no values)

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/cmrf_core#20]
When `_cmrf_views_civicrm_fields()` fetches fields of CiviCRM entities, it assumes the `field_name` being the array index of the returned values, see [this line](https://github.com/CiviMRF/cmrf_core/commit/baaa8184feec3f46e68449bf7d1e5c444b062dc7#diff-9ca6bbb572d7208e7d5c8d33f0f077ffR168).

The field name differs from the array index in some cases, e.g. when querying for `Membership.get` the `contact_id` field is being keyed with `membership_contact_id`. This leads to no results in the View when trying to display that field.

The field name should be set from the returned field property `name`.

**Comment by jensschuppe** [comment]
@jaapjansma Can you test some use cases for whether this works in all places? I think it should, since `name` is a property that must exist for every field and is also the API parameter name for CiviCRM entities, but maybe you're aware of some pitfalls with this approach.

**Comment by jaapjansma** [comment]
I think you are right. I haven't tested the fix yet. But will do when something comes along.

**Comment by jensschuppe** [comment]
Since we're still in a dev version (`0.x`), I'll merge this so it gets more tests in the wild.

**Comment by jensschuppe** [comment]
This has already been released with `7.x-0.12`.
