### ISSUE TITLE
Getting the base fields is not supported for entity type CMRF Datasets for Views

### ISSUE THREAD

**Issue by foadyousefi** [CiviMRF/cmrf_core#29]
Hi,

I've updated Drupal core to the latest version (8.9.1) and when I try to run `drush updb`, I'm getting an exception says: `Getting the base fields is not supported for entity type CMRF Datasets for Views` which causes to fail the deployment.

The exception caused by `views_post_update_field_names_for_multivalue_fields` function from Views module while it tries to update field names for multi-value base fields. 

Tracing the error, it seems that it happens in an `if` statement:
```php
if (!$entity_type->entityClassImplements(FieldableEntityInterface::class))
```

Here is the error log:
```
  [notice] Update started: views_post_update_field_names_for_multivalue_fields
  [error]  Getting the base fields is not supported for entity type CMRF Datasets for Views. 
  [error]  Update failed: views_post_update_field_names_for_multivalue_fields 
  [error]  Update aborted by: views_post_update_field_names_for_multivalue_fields 
  [error]  Finished performing updates. 
```

Some help appreciated.

**Comment by jensschuppe** [comment]
@foadyousefi I think you should post your issue on https://lab.civicrm.org/frontkom/cmrf_core_d8 which is a Drupal 8 port of this project.
