### ISSUE TITLE
[Views integration] Provide config entity installation in update hook implementation

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/cmrf_core#32]
The configuration entity _CMRF Dataset Relationship_ needs to be explicitly installed in an update hook implementation, see https://www.drupal.org/node/3034742#new-entity-type

**Comment by kainuk** [comment]
Hi @jensschuppe, I was looking into this issue. I need a more elaborate description. As I understand, you need to write an update hook when you change the entity definition (the magic that did the change automatically is gone). But the entity definition you mention has not changed for a long time. See https://git.drupalcode.org/project/cmrf_core/-/blame/2.0.x/cmrf_views/config/schema/cmrf_views.schema.yml . Is this something that must be still done, or is it a good practice for the future?

**Comment by jensschuppe** [comment]
Hi @kainuk and thanks for getting onto old issues!

I added the schema for the `cmrf_dataset_relationship` config entity quite some time ago with 4fda10bbb15c8cab7763d7f186e2ddd0dabe6a00 but did not know enough, at that time, about configuration schema and updating them in existing installations. So this is still missing an update hook implementation for adding that config entity to the active schema. However, new installations should not be affected.

However, I'm not sure this feature is actually being used by anyone. We, at least, took another approach for what this was trying to do and APIv4 is different anyway (by providing joins per API action), so maybe we can refactor out that bit again.

Some context: I wanted to provide "relationships" for CiviMRF Views Datasets as separate API calls which would then be available as a Views relationship for joining related CiviCRM entities in Views. This seemed to work (in some way) but I never really finished it. Also, this could easily get quite out of control resource-wise and does, by concept, not work well with filtering, grouping, sorting and paging the view.

**Comment by kainuk** [comment]
Hi @jensschuppe, I looked into this one in the context of creating an official release for 2.0.0. You describe this feature is not finished, so upgrade is certainly not needed.  So, I close this issue.

When I need a join, I mostly solve this now in CiviCRM. Until now, I use the dataprocessor for this, in the future maybe SearchKit. Performance is a good argument for this (less cmrf calls), but it is also nice that the website does not have to know too much about the CiviCRM internal structure.

**Comment by jensschuppe** [comment]
I totally agree. Would you be able to revert that commit and move it to a separate branch before releasing a `2.0.0` then, because this still causes an error message in the status report?

**Comment by kainuk** [comment]
Hi @jensschuppe, how do you create the status report (so I can check if my actions have effect).

**Comment by jensschuppe** [comment]
It's just an error message on `admin/reports/status` that pops up for installations that had CiviMRF installed before this commit went in. It should be enough to just revert the merge commit (009ac31a84efd74a000459854a1ed2fea05c0647), which introduced the module's config schema additions.

**Comment by kainuk** [comment]
Hi @jensschuppe, I have removed the relationship stuff in the following branch. If you have the time, can you do a short test.

**Comment by jensschuppe** [comment]
I checked that branch out and couldn't find any flaws, but I haven't had relationship stuff configured before, but I honestly wouldn't care for any leftover config, as this had neither ever been stable, nor documented anywhere. So let's merge that before `2.0.0`.

Thanks again for your efforts!

**Comment by jensschuppe** [comment]
@kainuk Didn't we want to include the removal of the code from the main branch in the `2.0` release branch? Let's merge it for `2.1` at least if you agree.
