### ISSUE TITLE
Clearing cache fails with 2.0.0-rc1

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/cmrf_core#43]
The code introduced with #42 makes clearing the cache fail due to this:
https://github.com/CiviMRF/cmrf_core/blob/507a2c0aaa25bced48a4efbdf08214faa8135c06/src/CallFactory.php#L22-L23

`getConnectors()` returns an array of connector labels keyed by their ID. Passing the label to `getConnectionProfile()` results in an exception that is not being caught.

The code should pass the array key instead.

**Comment by jensschuppe** [comment]
@kainuk Can you review this change? I can't clear caches without it, but I'm not sure whether it breaks something else.

**Comment by kainuk** [comment]
Hi @jensschuppe, you are right. The code as it is now, only works when the label the is the same as the key (what happens to be the case on my dev database). Should we change it to something like this: (also use the key in the delete statement)

 ```php
public function purgeCachedCalls() {
    parent::purgeCachedCalls();
    foreach($this->core->getConnectors() as $connector_id => $connector){
      $profile = $this->core->getConnectionProfile($connector_id);
      if ($profile['cache_expire_days'] > 0) {
        $today = new \DateTime();
        $today->modify('-'.$profile['cache_expire_days'].' days');
        $sql = "delete from {$this->table_name} where DATE(`create_date`) < '".$today->format('Y-m-d')."' AND `connector_id` = '".$connector_id."'";
        \Drupal::database()->query($sql);
      }
    }
  }
```

**Comment by jensschuppe** [comment]
@kainuk Of course, I forgot to check the entire code. I added a commit for fixing that and another one for reformatting to meet Drupal code standards. Would you re-review before we merge?

**Comment by jensschuppe** [comment]
I did some more testing, this seems to work fine, I'll merge this.

**Comment by jensschuppe** [comment]
Released with `2.0.0-rc2`

**Comment by kainuk** [comment]
Hi @jensschuppe, I also tested it. It works.

**Comment by jensschuppe** [comment]
Thanks for confirming, @kainuk!
