### ISSUE TITLE
Separate permission for accessing CMRF in Webforms

### ISSUE THREAD

**Issue by tbuytaer** [CiviMRF/cmrf_core#5]
Can we add a permission for accessing the CMRF settings in a Webform?
Currently everyone with edit access to webforms can change the CMRF settings.

[cmrf-webform.txt](https://github.com/CiviMRF/cmrf_core/files/1824845/cmrf-webform.txt)

**Comment by jaapjansma** [comment]
Sounds like a good plan. Can you submit your changes as a Pull request?

**Comment by tbuytaer** [comment]
OK, I created a Pull request for this: #6

**Comment by jaapjansma** [comment]
Thanks @tbuytaer
