### ISSUE TITLE
Support API 4

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/cmrf_core#57]
Once CiviMRF/CMRF_Abstract_Core#17 is done, supporting API 4 should be implemented for
* [x] *CiviMRF Views* - add a configuration option to the `cmrf_dataset` configuration entity for specifying the API version for the given entity/action
* [ ] *CiviMRF Webform* - add a configuration option to the `cmrf_webform_submission` configuration entity for specifying the API version for the given entity/action
* [x] *CiviMRF Call Report* - adjust output for API 4 request and reply objects

We'll first take care of the Views integration.

This is going to be Drupal-8-only for the time being and scheduled for [version `2.1.0`](https://github.com/CiviMRF/cmrf_core/milestone/6).

@dontub feel free to comment along here if you find something that needs discussion.

**Comment by kainuk** [comment]
Hi @jensschuppe with all these new ideas, it is a good moment to create an official 2.0 release. I would suggest to use just the current source for this. Or do I miss some bug?

**Comment by kainuk** [comment]
And another consideration is the place for the source code of this module. Initially we decided for Github, because we all know how to use it. However composer downloads it from drupal.org, so it the long run it will win. What is good moment for a switch?

**Comment by jensschuppe** [comment]
@kainuk well, there are #32 and #53, the latter of which creates an error message in the status report. Would you be able to look into those two and create a `2.0.0` release afterwards?

I would also plead for changing the required version of the abstract core in the `composer.json` too and release at least an alpha or beta version of the abstract core first, so we do not rely on a specific version here. What do you think?

I'd still keep development in GitHub for a while as it's easier for others to contribute, IMO. Maybe let's keep it in mind for the `2.1.0` release?

**Comment by jensschuppe** [comment]
Basic implementation and for the Views integration is in the `57-support-api-4` branch and can already be tested.

**Comment by jensschuppe** [comment]
We should raise Drupal core version requirements to at least `8.9` for the `2.1.0` release along with this.

**Comment by jensschuppe** [comment]
This has been mostly fixed by #59. Let's close here and open follow-up issues if necessary. Thanks, agian, @dontub!
