### ISSUE TITLE
`CMRFDatasetForm` should have method `exists`

### ISSUE THREAD

**Issue by dontub** [CiviMRF/cmrf_core#61]
The class `CMRFDatasetForm` should have a method named `exists` because it is called by `MachineName`:

> Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Drupal\cmrf_views\Form\CMRFDatasetForm' does not have a method 'exists' in Drupal\Core\Render\Element\MachineName::validateMachineName() (line 275 of core/lib/Drupal/Core/Render/Element/MachineName.php).

https://github.com/drupal/drupal/blob/5839fb2cab4ffe35911d614879e4ac7e6a5cf0ce/core/lib/Drupal/Core/Render/Element/MachineName.php#L275

**Comment by jensschuppe** [comment]
For reference, this has been worked on to be generic for config entities: https://www.drupal.org/project/drupal/issues/2091871

**Comment by kainuk** [comment]
On PHP 8.1 this is not a warning anymore but a blocking error. See https://www.drupal.org/project/cmrf_core/issues/3339619

**Comment by kainuk** [comment]
Is fixed in https://www.drupal.org/project/cmrf_core/releases/2.0.3
