### ISSUE TITLE
Tokens module and  CiviMRF View dataset conflict

### ISSUE THREAD

**Issue by Aly2191** [CiviMRF/cmrf_core#72]
Hi, 

Have a bug with how the CiviMRF view module interacts with https://www.drupal.org/project/token , have been able to reproduce on 2 separate installations. 

If a custom created token is used in the CiviMRF view dataset it causes several pages to break, and errors to be displayed on others. Mainly see it in adding content/ views with a page. 

Examples of pages broken 
node/add  (And seemingly any /node page). White screen error with the text displayed in contentError.txt  
When this error is present, in admin/content a warning message is displayed on top of the content (see attached file: View warning.txt)

Steps to reproduce: 
1)Create a user field via:  admin/config/people/accounts/fields]
[add field-> select field type [ Any type ,  currently replicated with number(integer) and text(plain)] 

2)Create a CiviMRF Connector with connecting module cmrf_views  
3)Create a dataset pulling from an api, with whatever fields needed, and then in the API parameters use the token to fill in some of the fields 
for ex { "user_id":"[current-user:field_anothertest:value]"}

4)Clear all caches in performance
5)And then try adding content in : /node/add

This should result in the error in attached contentError.txt, if the token is deleted or the token reference is removed from the dataset view the error resolves after a cache clear.

Please advise on best course of action. Potentially I'm filling in fields incorrectly? 

Thanks,
Aly

[contentError.txt](https://github.com/CiviMRF/cmrf_core/files/13474052/contentError.txt)
[enabled modules and versions.txt](https://github.com/CiviMRF/cmrf_core/files/13474066/enabled.modules.and.versions.txt)

**Comment by jensschuppe** [comment]
@jaapjansma is this related to what you fixed with 746bf6fd1dd06f053adb59a290ad4f286557ffb2?

**Comment by jaapjansma** [comment]
Yes indeed it is related. And I fixed it for @Aly2191 and also for another client of mine.
